apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "data/postgres"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: ewnb3X8LJ%u%bq8+uMhavLW5b*c
  POSTGRES_USER: admin
  POSTGRES_DB: production

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres-image
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-sql
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
      volumes:
        - name: postgres-sql
          hostPath:
            path: /postgres/sql
            type: DirectoryOrCreate
